name: C++ CI

on:
  pull_request:
    branches: [ block3 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build and run tests
        working-directory: ./src
        run: |
          make test
          ./testik
